version: "3.7"

services:
  convert:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - logs:/home/user/logs

volumes:
  logs:
