version: "3.7"

services:
  convert:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - logs:/home/user/logs
  monitor:
    image: ghcr.io/luomus/log-monitor
    restart: unless-stopped
    environment:
      - "PAGE_TITLE='finbif-geo-convert'"
    ports:
      - "3838:3838"
    volumes:
      - logs:/home/user/logs
    depends_on:
      - convert

volumes:
  logs:
