#!/bin/bash

if ! command -v docker &> /dev/null
then
    echo "docker runtime could not be found"
    exit
fi

docker run --rm \
  -u $(id -u) \
  -v $PWD:/home/user \
  ghcr.io/luomus/finbif-geo-convert \
  convert \
  "$@"
