kind: Template
apiVersion: template.openshift.io/v1
parameters:
  - name: APP
    required: true
    value: finbif-geo-convert
  - name: PAGE_TITLE
    required: true
    value: "FinBIF Geo-convert"
  - name: APP_PORT
    required: true
    value: "8000"
  - name: APP_HEALTHCHECK
    required: true
    value: /healthz
  - name: FILE_SIZE_LIMIT
    required: true
    value: "2e8"
  - name: BRANCH
    required: true
  - name: FINBIF_PRIVATE_API
    required: true
  - name: HOST
    required: true
  - name: SMTP_SERVER
    required: true
  - name: SMTP_PORT
    required: true
  - name: ERROR_EMAIL_TO
    required: true
  - name: ERROR_EMAIL_FROM
    required: true
  - name: GITHUB_SECRET
    required: true
    generate: expression
    from: "[a-zA-Z0-9]{20}"
metadata:
  name: ${APP}
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${APP}-${BRANCH}
    labels:
      app: ${APP}
  spec:
    lookupPolicy:
      local: true
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${APP}-${BRANCH}
    labels:
      app: ${APP}
  spec:
    resources:
      limits:
        cpu: "1000m"
        memory: "2Gi"
    output:
      to:
        kind: ImageStreamTag
        name: ${APP}-${BRANCH}:latest
    source:
      type: Git
      git:
        uri: https://github.com/luomus/${APP}.git
        ref: ${BRANCH}
    strategy:
      type: Docker
    triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: ${GITHUB_SECRET}
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: ${APP}-${BRANCH}
    labels:
      app: ${APP}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${APP}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${APP}
          branch: ${BRANCH}
      spec:
        containers:
        - image: ${APP}-${BRANCH}:latest
          name: ${APP}-${BRANCH}
          ports:
          - containerPort: ${{APP_PORT}}
          startupProbe:
            httpGet:
              path: ${APP_HEALTHCHECK}
              port: ${{APP_PORT}}
            failureThreshold: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: ${APP_HEALTHCHECK}
              port: ${{APP_PORT}}
            failureThreshold: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: ${APP_HEALTHCHECK}
              port: ${{APP_PORT}}
            periodSeconds: 5
          env:
          - name: BRANCH
            value: ${BRANCH}
          - name: PAGE_TITLE
            value: ${PAGE_TITLE}
          - name: FINBIF_FILE_SIZE_LIMIT
            value: ${FILE_SIZE_LIMIT}
          - name: FINBIF_PRIVATE_API
            value: ${FINBIF_PRIVATE_API}
          - name: FINBIF_USE_PRIVATE_API
            value: "true"
          - name: FINBIF_USER_AGENT
            value: https://github.com/luomus/${APP}.git
          - name: SMTP_SERVER
            value: ${SMTP_SERVER}
          - name: SMTP_PORT
            value: ${SMTP_PORT}
          - name: ERROR_EMAIL_TO
            value: ${ERROR_EMAIL_TO}
          - name: ERROR_EMAIL_FROM
            value: ${ERROR_EMAIL_FROM}
          resources:
            limits:
              cpu: "1500m"
              memory: "7Gi"
- kind: Service
  apiVersion: v1
  metadata:
    name: ${APP}-${BRANCH}
    labels:
      app: ${APP}
  spec:
    ports:
    - name: ${APP_PORT}
      port: ${{APP_PORT}}
      targetPort: ${{APP_PORT}}
    selector:
      app: ${APP}
      branch: ${BRANCH}
- kind: Route
  apiVersion: v1
  metadata:
    name: ${APP}-${BRANCH}
    labels:
      app: ${APP}
  spec:
    host: ${HOST}
    port:
      targetPort: ${{APP_PORT}}
    to:
      kind: Service
      name: ${APP}-${BRANCH}
    tls:
      insecureEdgeTerminationPolicy: Redirect
